<a href="https://colab.research.google.com/github/ktcraig/neural-network-challenge-2/blob/main/UPDATED_attrition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Part 1: Preprocessing

In [67]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras import layers, models, Model
from tensorflow.keras import layers
!pip install --upgrade scikit-learn

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn) (3.6.0)

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,Research & Development,23,2,Medical,3,41,4,...,3,3,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,Research & Development,6,1,Medical,4,42,2,...,3,1,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,Research & Development,4,3,Life Sciences,2,87,4,...,4,2,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,Sales,2,3,Medical,4,63,2,...,3,4,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,Research & Development,8,3,Medical,2,82,4,...,3,1,0,6,3,4,4,3,1,2

In [68]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [69]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df

     Attrition              Department
0          Yes                   Sales
1           No  Research & Development
2          Yes  Research & Development
3           No  Research & Development
4           No  Research & Development
...        ...                     ...
1465        No  Research & Development
1466        No  Research & Development
1467        No  Research & Development
1468        No                   Sales
1469        No  Research & Development

[1470 rows x 2 columns]

In [70]:
# Create a list of at least 10 column names to use as X data
x = ['Age',
     'OverTime',
     'YearsAtCompany',
     'DistanceFromHome',
     'Education',
     'EducationField',
     'EnvironmentSatisfaction',
     'HourlyRate',
     'JobInvolvement',
     'JobLevel']

# Create X_df using your selected columns
x_df = attrition_df[x]

# Show the data types for X_df
x_df

,Age,OverTime,YearsAtCompany,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel
0,41,Yes,6,1,2,Life Sciences,2,94,3,2
1,49,No,10,8,1,Life Sciences,3,61,2,2
2,37,Yes,0,2,2,Other,4,92,2,1
3,33,Yes,8,3,4,Life Sciences,4,56,3,1
4,27,No,2,2,1,Medical,1,40,3,1
...,...,...,...,...,...,...,...,...,...,...
1465,36,No,5,23,2,Medical,3,41,4,2
1466,39,No,7,6,1,Medical,4,42,2,3
1467,27,Yes,6,4,3,Life Sciences,2,87,4,2
1468,49,No,9,2,3,Medical,4,63,2,2
1469,34,No,4,8,3,Medical,2,82,4,2

In [71]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_df, y_df, test_size=0.2, random_state=42)

In [72]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

In [73]:
# Import dependencies
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

# Create a OneHotEncoder instance
encoder = OneHotEncoder(sparse_output=False, drop=None)

# Select categorical columns that need to be encoded
categorical_cols = ['OverTime', 'EducationField']

# Fit the encoder on the 'OverTime' column
encoder.fit(np.array(x_train['OverTime']).reshape(-1, 1))

# Transform the 'OverTime' column for x_train and x_test
over_time_encoded_train = encoder.transform(np.array(x_train['OverTime']).reshape(-1, 1))
over_time_encoded_test = encoder.transform(np.array(x_test['OverTime']).reshape(-1, 1))

# Create DataFrames for the encoded columns
over_time_train_df = pd.DataFrame(over_time_encoded_train, columns=encoder.get_feature_names_out(['OverTime']))
over_time_test_df = pd.DataFrame(over_time_encoded_test, columns=encoder.get_feature_names_out(['OverTime']))

# Concatenate the new columns to the original DataFrames
x_train = pd.concat([x_train, over_time_train_df], axis=1)
x_test = pd.concat([x_test, over_time_test_df], axis=1)

# Drop the original OverTime column from the DataFrames
x_train.drop(columns="OverTime", inplace=True)
x_test.drop(columns="OverTime", inplace=True)

In [74]:
# Import dependencies
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np

# Create a OneHotEncoder instance
encoder = OneHotEncoder(sparse_output=False, drop=None)

# Select categorical columns that need to be encoded
categorical_cols = ['OverTime', 'EducationField']

# Fit the encoder on the 'OverTime' column
encoder.fit(np.array(x_train['EducationField']).reshape(-1, 1))

# Transform the 'OverTime' column for x_train and x_test
over_time_encoded_train = encoder.transform(np.array(x_train['EducationField']).reshape(-1, 1))
over_time_encoded_test = encoder.transform(np.array(x_test['EducationField']).reshape(-1, 1))

# Create DataFrames for the encoded columns
over_time_train_df = pd.DataFrame(over_time_encoded_train, columns=encoder.get_feature_names_out(['EducationField']))
over_time_test_df = pd.DataFrame(over_time_encoded_test, columns=encoder.get_feature_names_out(['EducationField']))

# Concatenate the new columns to the original DataFrames
x_train = pd.concat([x_train, over_time_train_df], axis=1)
x_test = pd.concat([x_test, over_time_test_df], axis=1)

# Drop the original OverTime column from the DataFrames
x_train.drop(columns="EducationField", inplace=True)
x_test.drop(columns="EducationField", inplace=True)

In [75]:
# Create a Standard Scaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(x_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(x_train)
X_test_scaled = X_scaler.transform(x_test)

X_train_scaled

array([[-1.38855944, -0.97426331,  1.44039645, ..., -0.22599398,
        -0.27671856, -0.45550301],
       [-2.04073779, -1.13857331, -0.52269928, ..., -0.22599398,
        -0.27671856, -0.45550301],
       [-0.84507748, -0.6456433 ,  1.31770296, ..., -0.22599398,
        -0.27671856, -0.45550301],
       ...,
       [        nan,         nan,         nan, ..., -0.22599398,
        -0.27671856,  2.19537517],
       [        nan,         nan,         nan, ..., -0.22599398,
        -0.27671856,  2.19537517],
       [        nan,         nan,         nan, ..., -0.22599398,
        -0.27671856,  2.19537517]])

In [76]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
encoder = OneHotEncoder(sparse_output=False, drop= None)

# Fit the encoder to the training data
encoder.fit(np.array(y_train[['Department']]))

# Create two new variables by applying the encoder to the training and testing data
y_train_encoded_department = encoder.transform(np.array(y_train[['Department']]))
y_test_encoded_department = encoder.transform(np.array(y_test[['Department']]))

y_train_encoded_department

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [77]:
# Create a OneHotEncoder for the Attrition column
encoder = OneHotEncoder(sparse_output=False, drop= None)

# Fit the encoder to the training data
encoder.fit(np.array(y_train[['Attrition']]))

# Create two new variables by applying the encoder to the training and testing data
y_train_encoded_attrition = encoder.transform(np.array(y_train[['Attrition']]))
y_test_encoded_attrition = encoder.transform(np.array(y_test[['Attrition']]))

y_train_encoded_attrition

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [83]:
# Find the number of columns in the X training data
num_features = len(x_train.columns)
print(num_features)

# Create the input layer with the correct shape
input_layer = layers.Input(shape=(num_features,), name='input_layer')

# Create at least 2 shared layers using Dense layers
shared_layer1 = layers.Dense(64, activation='relu')(input_layer)
shared_layer2 = layers.Dense(128, activation='relu')(shared_layer1)

17

In [84]:
# Create a branch for 'Department' with a hidden layer and an output layer
# Get the number of columns (classes) from the shape of y_train_encoded

#Hidden Layer
department_dense = layers.Dense(64, activation='relu')(shared_layer1)
#Output Layer
department_output = layers.Dense(y_train_encoded_department.shape[1],
                                 activation='sigmoid',
                                 name='department_output')(department_dense)

In [85]:
# Create a branch for 'Attrition' with a hidden layer and an output layer
# Get the number of columns (classes) from the shape of y_train_encoded

#Hidden Layer
attrition_dense = layers.Dense(64, activation='relu')(shared_layer1)
#Output Layer
attrition_output = layers.Dense(y_train_encoded_attrition.shape[1],
                                activation='sigmoid',
                                name='attrition_output')(attrition_dense)

In [86]:
# Create the model
model = Model(inputs=input_layer, outputs=[department_output, attrition_output])

# Compile the model
model.compile(optimizer='adam',
              loss={'department_output': 'categorical_crossentropy',
                    'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy',
                       'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)  │ (None, 17)             │              0 │ -                      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_21 (Dense)          │ (None, 64)             │          1,152 │ input_layer[0][0]      │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_23 (Dense)          │ (None, 64)             │          4,160 │ dense_21[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_24 (Dense)          │ (None, 64)             │          4,160 │ dense_21[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ department_output (Dense) │ (None, 3)              │            195 │ dense_23[0][0]         │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ attrition_output (Dense)  │ (None, 2)              │            130 │ dense_24[0][0]         │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 9,797 (38.27 KB)

 Trainable params: 9,797 (38.27 KB)

 Non-trainable params: 0 (0.00 B)

In [88]:
# Train the model
"""Colab Assistance Source Code""""
model.fit(
    X_train_scaled[:len(y_train_encoded_department)], # Slice X_train_scaled to match the length of y data
    {'department_output': y_train_encoded_department,
     'attrition_output': y_train_encoded_attrition},
    epochs=10,
    batch_size=32,
)

Epoch 1/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - attrition_output_accuracy: 0.7829 - attrition_output_loss: nan - department_output_accuracy: 0.0698 - department_output_loss: nan - loss: nan
Epoch 2/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8469 - attrition_output_loss: nan - department_output_accuracy: 0.0493 - department_output_loss: nan - loss: nan
Epoch 3/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8340 - attrition_output_loss: nan - department_output_accuracy: 0.0468 - department_output_loss: nan - loss: nan
Epoch 4/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8371 - attrition_output_loss: nan - department_output_accuracy: 0.0557 - department_output_loss: nan - loss: nan
Epoch 5/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8399 - attrition_output_loss: nan - department_output_accuracy: 0.0500 - department_output_loss: nan - loss: nan
Epoch 6/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8445 - attrition_output_loss: nan - department_output_accuracy: 0.0428 - department_output_loss: nan - loss: nan
Epoch 7/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8387 - attrition_output_loss: nan - department_output_accuracy: 0.0431 - department_output_loss: nan - loss: nan
Epoch 8/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8231 - attrition_output_loss: nan - department_output_accuracy: 0.0522 - department_output_loss: nan - loss: nan
Epoch 9/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8206 - attrition_output_loss: nan - department_output_accuracy: 0.0447 - department_output_loss: nan - loss: nan
Epoch 10/10
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8540 - attrition_output_loss: nan - department_output_accuracy: 0.0450 - department_output_loss: nan - loss: nan

In [93]:
# Evaluate the model with testing data
results = model.evaluate(X_test_scaled[:len(y_test_encoded_department)],
                         {'department_output': y_test_encoded_department,
                          'attrition_output': y_test_encoded_attrition})

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8447 - attrition_output_loss: nan - department_output_accuracy: 0.0424 - department_output_loss: nan - loss: nan

In [94]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {results[3]}")
print(f"Attrition Accuracy: {results[3]}")

Department Accuracy: 0.8673469424247742
Attrition Accuracy: 0.8673469424247742

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. I believe that accuracy is the metric to use on this data because you are trying to determine how accurate you can predict how likely employees are to leave the company. I am skeptical of the results though because I may have used different columns than the original code and the numbers in the model are different than the original output in the starter code.
2. I used sigmoid activation. I used sigmoid activation because to predict accuracy I wanted an output ranging from 0 to 1.
3. I had a lot of issues with the different types of data within the initial dataframe that I could not resolve cleanly just through one hot encoder or standard scaler. In hindsight, I would select different columns from the dataframe to avoid so much processing later on in my code.